language: cpp

compiler:
  - gcc
  - clang

os: linux

dist: trusty

sudo: required

notifications:
  email: false

branches:
  only:
    - master
    - /^.*travis.*$/

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential cmake git libevent-dev libboost-all-dev libpcap-dev libyaml-cpp-dev

install:
  - git clone https://github.com/google/re2.git
  - cd re2 && make && sudo make install

before_script: cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script: make